# Default post title
default_post_title: Azure Past

#Date Format
date_format: YYYY 年 MM 月 DD 日

# Comment.
comments:
  # Disqus comment
  disqus_shortname: azure past

# Google Analytics Tracking ID
google_analytics:
 
